# Default backtest configuration
backtest:
  signal:
    long_threshold: 0.6
    short_threshold: 0.4
    position_sizing: fixed
    position_size: 1.0
    kelly_fraction: 0.25
    max_position: 10.0
  
  execution:
    transaction_cost: 0.001
    slippage: 0.0005
    max_position: 10.0
    min_trade_size: 0.1
    execution_delay: 1
  
  metrics:
    risk_free_rate: 0.02
    benchmark_return: 0.0
    trading_days: 252



